# SPDX-FileCopyrightText: 2016-2022 2016 Nick Sellen, <hello@nicksellen.co.uk> et al.
#
# SPDX-License-Identifier: MIT

[book]
title = "Karrot Developer Documentation"
author = "Karrot Team"
description = "Documentation for Karrot developers."
src = "src"
language = "en"
